$ npm start

> ddk@0.9.9-a start /var/app/DDK/DDKCoin
> node app.js

info: Starting the collection of metrics, the metrics are available on /metrics
info: App connected with redis server
info: typeID : 3
info: asset type is attached successfully
info: typeID : 0
info: asset type is attached successfully
info: typeID : 11
info: asset type is attached successfully
info: typeID : 1
info: asset type is attached successfully
info: typeID : 2
info: asset type is attached successfully
info: typeID : 4
info: asset type is attached successfully
info: typeID : 5
info: asset type is attached successfully
info: typeID : 6
info: asset type is attached successfully
info: typeID : 7
info: asset type is attached successfully
info: typeID : 9
info: asset type is attached successfully
info: typeID : 8
info: asset type is attached successfully
info: typeID : 10
info: asset type is attached successfully
info: ddk started: 127.0.0.1:7001
info: Modules ready and launched
Nodemailer Error:  { Error: Missing credentials for "CRAM-MD5"
    at SMTPConnection._formatError (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection.login (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-connection/index.js:350:38)
    at connection.connect (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-transport/index.js:373:32)
    at SMTPConnection.once (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-connection/index.js:188:17)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at SMTPConnection.emit (events.js:207:7)
    at SMTPConnection._actionEHLO (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-connection/index.js:1128:14)
    at SMTPConnection._processResponse (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
    at SMTPConnection._onData (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
    at Socket._socket.on.chunk (/var/app/DDK/DDKCoin/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10) code: 'EAUTH', command: 'API' }
info: Blocks 5484856
info: Genesis block matched with database
info: Blockchain ready
info: Loading 3 delegates from config
info: Imported peers from database count=0
info: Starting sync
info: Broadhash consensus now 0 %
error: Discovering new peers failed No acceptable peers found
info: Finished sync
error: error: column "acc_type" does not exist
    at Connection.parseE (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
info: Starting sync
error: Failed to load delegates Account#getAll error
info: Loading 3 delegates from config
info: Broadhash consensus now 0 %
info: Finished sync
error: error: column "acc_type" does not exist
    at Connection.parseE (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
info: Starting sync
info: Broadhash consensus now 0 %
info: Finished sync
info: Starting sync
info: Broadhash consensus now 0 %
info: Finished sync
info: Starting sync
info: Broadhash consensus now 0 %
info: Finished sync
error: Sync timer Failed to find enough good peers
error: Failed to load delegates Account#getAll error
info: Loading 3 delegates from config
error: error: column "acc_type" does not exist
    at Connection.parseE (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```

```
info: Finished sync
error: Sync timer Failed to find enough good peers
error: Failed to load delegates Account#getAll error
info: Loading 3 delegates from config
error: elasticsearch error : message=Request Timeout after 30000ms, status=408, displayName=RequestTimeout, stack=Error: Request Timeout after 30000ms
    at /var/app/DDK/DDKCoin/node_modules/elasticsearch/src/lib/transport.js:354:15
    at Timeout._onTimeout (/var/app/DDK/DDKCoin/node_modules/elasticsearch/src/lib/transport.js:383:7)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
error: error: column "acc_type" does not exist
    at Connection.parseE (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
info: Starting sync

<--- Last few GCs --->

[9388:0x424c420]   375483 ms: Mark-sweep 1407.2 (1465.5) -> 1407.1 (1442.0) MB, 2932.2 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2932 ms) last resort 
[9388:0x424c420]   378558 ms: Mark-sweep 1407.1 (1442.0) -> 1407.1 (1442.0) MB, 3074.0 / 0.0 ms  last resort 


<--- JS stacktrace --->


==== JS stack trace =========================================

Security context: 0x3c62bb528799 <JSObject>
    1: emit [events.js:~155] [pc=0x1e1582c1cba3](this=0xbb3eeb69251 <Connection map = 0x26d1d463a5f1>,type=0x1ca0af7fba11 <String[7]: dataRow>)
    2: arguments adaptor frame: 2->1
    3: /* anonymous */ [/var/app/DDK/DDKCoin/node_modules/pg-promise/node_modules/pg/lib/connection.js:~101] [pc=0x1e1582c06c43](this=0xff7083ffbb1 <Socket map = 0x26d1d4639201>,buff=0x37cc783a051 <Uint8Array map = 0x...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x13576dc [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewStruct(v8::internal::InstanceType) [node]
 6: v8::internal::Factory::NewTuple3(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
 7: v8::internal::LoadIC::LoadFromPrototype(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Smi>) [node]
 8: v8::internal::LoadIC::GetMapIndependentHandler(v8::internal::LookupIterator*) [node]
 9: v8::internal::IC::ComputeHandler(v8::internal::LookupIterator*) [node]
10: v8::internal::LoadIC::UpdateCaches(v8::internal::LookupIterator*) [node]
11: v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [node]
12: v8::internal::Runtime_LoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [node]
13: 0x1e1582a046fd
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ddk@0.9.9-a start: `node app.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the ddk@0.9.9-a start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/werd/.npm/_logs/2018-07-12T08_29_13_382Z-debug.log